### ISSUE TITLE
Could you teach me how to solve the problem(UnicodeDecodeError)?

### ISSUE THREAD

**Issue by pcmola** [bricklife/LEGO-Hub2Hub-Communication-Hacks#1]
Hi. 

Thanks to your guide, I'm trying to connect to Mindstorms hub.
I faced the following issue.

>  $ sudo python3 hub2hub.py receive
Traceback (most recent call last):
  File "hub2hub.py", line 102, in <module>
    receive_signal(_callback)
  File "hub2hub.py", line 65, in receive_signal
    bluez.hci_filter_all_events(flt)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 4: invalid start byte

Do you know how to solve this problem?

**Comment by pcmola** [comment]
Before this, I installed the bluetooth module .

`$ sudo python3 hub2hub.py receive`
`Traceback (most recent call last):`
`  File "hub2hub.py", line 1, in <module>`
`    import bluetooth._bluetooth as bluez`
`ModuleNotFoundError: No module named 'bluetooth'`

`$ git clone https://github.com/pybluez/pybluez.git`
`$ cd pybluez/`
`~/pybluez $ sudo python3 setup.py install`

**Comment by SpudGunMan** [comment]
you likely figured it out but to install you want to 

```
sudo apt-get install bluetooth libbluetooth-dev
sudo python3 -m pip install pybluez

```

this is likely worth adding to the readme.md
